package git

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

// Committer generates ArgoCD Application manifests and commits them to git.
type Committer struct {
	repoDir string
}

// NewCommitter creates a Committer targeting the given git repository directory.
func NewCommitter(repoDir string) *Committer {
	return &Committer{repoDir: repoDir}
}

const argoAppTemplate = `apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Name }}
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: environment-provisioning-portal
    portal/environment: {{ .Name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .RepoURL }}
    targetRevision: HEAD
    path: gitops/apps/{{ .Name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
`

// argoAppData holds template values.
type argoAppData struct {
	Name      string
	Namespace string
	RepoURL   string
}

// CommitArgoApp generates an ArgoCD Application manifest for the given environment
// and commits it to the gitops/apps/<name>/ directory.
func (c *Committer) CommitArgoApp(envName, namespace string) error {
	// Parse and execute template.
	tmpl, err := template.New("argocd").Parse(argoAppTemplate)
	if err != nil {
		return fmt.Errorf("parse argo template: %w", err)
	}

	// Try to detect the repo URL from git remote.
	repoURL := c.detectRemoteURL()
	if repoURL == "" {
		repoURL = "https://github.com/example/environment-provisioning-portal.git"
	}

	data := argoAppData{
		Name:      envName,
		Namespace: namespace,
		RepoURL:   repoURL,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return fmt.Errorf("execute argo template: %w", err)
	}

	// Write manifest file.
	appDir := filepath.Join(c.repoDir, "gitops", "apps", envName)
	if err := os.MkdirAll(appDir, 0o755); err != nil {
		return fmt.Errorf("create app dir: %w", err)
	}

	manifestPath := filepath.Join(appDir, "application.yaml")
	if err := os.WriteFile(manifestPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}

	// Git add + commit.
	if err := c.gitAddAndCommit(manifestPath, envName); err != nil {
		return fmt.Errorf("git commit: %w", err)
	}

	return nil
}

// gitAddAndCommit stages the file and creates a commit.
func (c *Committer) gitAddAndCommit(filePath, envName string) error {
	relPath, err := filepath.Rel(c.repoDir, filePath)
	if err != nil {
		relPath = filePath
	}

	commands := [][]string{
		{"git", "add", relPath},
		{"git", "commit", "-m", fmt.Sprintf("provision: add ArgoCD application for %s\n\nGenerated by Environment Provisioning Portal", envName)},
	}

	for _, args := range commands {
		cmd := exec.Command(args[0], args[1:]...)
		cmd.Dir = c.repoDir
		cmd.Env = append(os.Environ(),
			"GIT_AUTHOR_NAME=Environment Portal",
			"GIT_AUTHOR_EMAIL=portal@internal.dev",
			"GIT_COMMITTER_NAME=Environment Portal",
			"GIT_COMMITTER_EMAIL=portal@internal.dev",
		)
		out, err := cmd.CombinedOutput()
		if err != nil {
			return fmt.Errorf("%s: %s: %w", args[1], string(out), err)
		}
	}
	return nil
}

// detectRemoteURL tries to get the origin remote URL from the git repo.
func (c *Committer) detectRemoteURL() string {
	cmd := exec.Command("git", "remote", "get-url", "origin")
	cmd.Dir = c.repoDir
	out, err := cmd.Output()
	if err != nil {
		return ""
	}
	return string(bytes.TrimSpace(out))
}
